module.exports = [
  { id: "2020-reelection", label: "2020 Reelection" },
  { id: "affordable-housing", label: "Affordable Housing" },
  { id: "african-american-studies", label: "African American Studies" },
  { id: "anti-establishment", label: "Anti-Establishment" },
  { id: "anti-trump", label: "Anti-Trump" },
  { id: "approach", label: "Approach" },
  { id: "appropriations", label: "Appropriations" },
  { id: "aquaculture", label: "Aquaculture" },
  { id: "blue-economy", label: "Blue Economy" },
  { id: "budget", label: "Budget" },
  { id: "budget-discipline", label: "Budget Discipline" },
  { id: "cmp-controversy", label: "CMP Controversy" },
  { id: "child-care", label: "Child Care" },
  { id: "child-hunger", label: "Child Hunger" },
  { id: "child-welfare", label: "Child Welfare" },
  { id: "civil-legal-aid", label: "Civil Legal Aid" },
  { id: "civil-liberties", label: "Civil Liberties" },
  { id: "climate", label: "Climate" },
  { id: "continuing-dhalacs-legacy", label: "Continuing Dhalac's Legacy" },
  { id: "cost-of-living", label: "Cost of Living" },
  { id: "county-services", label: "County Services" },
  { id: "day-one-eos", label: "Day One EOs" },
  { id: "democracy", label: "Democracy" },
  { id: "democracy-civil-rights", label: "Democracy & Civil Rights" },
  { id: "democracy-reform", label: "Democracy Reform" },
  { id: "disability-rights", label: "Disability Rights" },
  { id: "drug-prices", label: "Drug Prices" },
  { id: "economic-new-deal", label: "Economic New Deal" },
  { id: "economy-taxes", label: "Economy & Taxes" },
  { id: "education", label: "Education" },
  { id: "election-administration", label: "Election Administration" },
  { id: "energy", label: "Energy" },
  { id: "energy-costs", label: "Energy Costs" },
  { id: "environment", label: "Environment" },
  { id: "environmental-protection", label: "Environmental Protection" },
  { id: "firearm-safety", label: "Firearm Safety" },
  { id: "fiscal-conservative", label: "Fiscal Conservative" },
  { id: "foster-care-reform", label: "Foster Care Reform" },
  { id: "government-effectiveness", label: "Government Effectiveness" },
  { id: "gun-safety", label: "Gun Safety" },
  { id: "health-equity", label: "Health Equity" },
  { id: "healthcare", label: "Healthcare" },
  { id: "healthcare-access", label: "Healthcare Access" },
  { id: "housing", label: "Housing" },
  { id: "housing-first", label: "Housing First" },
  { id: "ice-detainers", label: "ICE Detainers" },
  { id: "immigration", label: "Immigration" },
  { id: "impeachment-votes", label: "Impeachment Votes" },
  { id: "iran", label: "Iran" },
  { id: "iran-war", label: "Iran War" },
  { id: "juvenile-justice", label: "Juvenile Justice" },
  { id: "labor", label: "Labor" },
  { id: "labor-workers", label: "Labor & Workers" },
  { id: "limited-public-information", label: "Limited public information" },
  { id: "limited-public-platform", label: "Limited public platform" },
  { id: "maine-2040-plan", label: "Maine 2040 Plan" },
  { id: "mainecare", label: "MaineCare" },
  { id: "mental-health", label: "Mental Health" },
  { id: "message", label: "Message" },
  { id: "minimum-wage", label: "Minimum Wage" },
  { id: "no-public-platform", label: "No public platform" },
  { id: "oil-terminal-notification", label: "Oil Terminal Notification" },
  { id: "opioid-epidemic", label: "Opioid Epidemic" },
  { id: "policy-agenda", label: "Policy Agenda" },
  { id: "property-tax", label: "Property Tax" },
  { id: "property-tax-relief", label: "Property Tax Relief" },
  { id: "property-taxes", label: "Property Taxes" },
  { id: "rcv-alliance", label: "RCV Alliance" },
  { id: "rcv-strategy", label: "RCV Strategy" },
  { id: "racial-equity", label: "Racial Equity" },
  { id: "racial-impact-assessments", label: "Racial Impact Assessments" },
  { id: "reproductive-choice", label: "Reproductive Choice" },
  { id: "rural-healthcare", label: "Rural Healthcare" },
  { id: "small-business", label: "Small Business" },
  { id: "social-programs", label: "Social Programs" },
  { id: "state-budget", label: "State Budget" },
  { id: "tax-cuts", label: "Tax Cuts" },
  { id: "taxes", label: "Taxes" },
  { id: "tenant-rights", label: "Tenant Rights" },
  { id: "term-limits", label: "Term Limits" },
  { id: "trans-athlete-policy", label: "Trans Athlete Policy" },
  { id: "tribal-courts", label: "Tribal Courts" },
  { id: "tribal-sovereignty", label: "Tribal Sovereignty" },
  { id: "trump", label: "Trump" },
  { id: "trump-relationship", label: "Trump Relationship" },
  { id: "ukraine", label: "Ukraine" },
  { id: "venezuela-war-powers", label: "Venezuela War Powers (Jan 2026)" },
  { id: "veterans", label: "Veterans" },
  { id: "wabanaki-sovereignty", label: "Wabanaki Sovereignty" },
  { id: "welfare", label: "Welfare" },
  { id: "windham-connection", label: "Windham Connection" },
  { id: "worker-rights", label: "Worker Rights" },
  { id: "workers-rights", label: "Workers' Rights" }
];